name: 'PR Scan: CVE Policy Check'

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  opa-policy-check:
    name: 'OPA CVE Policy Check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout PR Code'
        uses: actions/checkout@v4

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Build Container Image Locally'
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: pr-scan-image:latest
          file: ./Containerfile

      - name: 'Check for Root User at Runtime'
        run: |
          echo "Verifying container runs as non-root user..."
          # Execute 'id -u' inside the container to get the user ID.
          USER_ID=$(docker run --rm pr-scan-image:latest id -u)
          
          echo "Container UID is: $USER_ID"
          if [ "$USER_ID" = "0" ]; then
            echo "❌ Policy Check Failed: Container must not run as root (UID 0)."
            exit 1
          else
            echo "✅ Policy Check Passed: Container runs as a non-root user."
          fi

      - name: 'Install Anchore Grype'
        uses: anchore/scan-action/download-grype@v3

      - name: 'Run CVE Scan with Grype'
        run: grype pr-scan-image:latest -o json > cve-report.json

      - name: 'Upload CVE Report as Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: cve-report
          path: cve-report.json

      - name: 'Install OPA'
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/v0.66.0/opa_linux_amd64_static
          chmod +x ./opa

      - name: 'Evaluate CVE report against OPA policy'
        run: |
          echo "Evaluating policy: deny if High or Critical CVEs exist..."

          # First, ask OPA for the set of violation messages.
          VIOLATIONS_RESULT=$(./opa eval \
            --data .github/policies/deny.rego \
            --input cve-report.json \
            "data.grype.authz.violations")
          
          # Next, use jq to extract just the array of violation messages from OPA's JSON output.
          VIOLATIONS_ARRAY=$(echo "$VIOLATIONS_RESULT" | jq '.result[0].expressions[0].value')

          # Now, check if the length of the violation array is greater than zero.
          if [ "$(echo "$VIOLATIONS_ARRAY" | jq 'length')" -gt 0 ]; then
            # This block runs if the violations array is NOT empty.
            echo "❌ OPA Policy Check Failed! Found High or Critical CVEs."
            echo "Found violations:"
            # Pretty-print each violation from the array.
            echo "$VIOLATIONS_ARRAY" | jq --raw-output '.[]'
            exit 1
          else
            # This block runs if the violations array is empty.
            echo "✅ OPA Policy Check Passed. No High or Critical CVEs found."
          fi

  containerfile-policy-check:
    name: 'Containerfile Policy Check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout PR Code'
        uses: actions/checkout@v4

      - name: 'Install conftest'
        run: |
          curl -L -o conftest https://github.com/open-policy-agent/conftest/releases/download/v0.52.0/conftest_0.52.0_Linux_x86_64.tar.gz
          tar -xzf conftest
          sudo mv conftest /usr/local/bin/

      # This step has been REMOVED from the workflow.
      # - name: 'Create OPA policy for non-root user check'

      - name: 'Check Containerfile against non-root policy'
        run: |
          echo "Checking Containerfile for root user..."
          # Update the policy path to point to the directory containing your Rego files.
          conftest test --policy .github/policies Containerfile
