name: Reusable OCI Attestor and Publisher

on:
  workflow_call:
    inputs:
      image_name_with_tag:
        required: true
        type: string
      image_name_no_tag: # e.g., github_owner/image_name
        required: true
        type: string
      image_digest:
        required: true
        type: string
      sbom_cyclonedx_path:
        required: true
        type: string
      sbom_spdx_path:
        required: true
        type: string
      sbom_syft_json_path:
        required: true
        type: string
      cve_report_path:
        required: true
        type: string

permissions:
  actions: read
  contents: read
  id-token: write
  attestations: write
  packages: write

jobs:
  attest_and_publish_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts (SBOMs, CVE report)
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./downloaded-artifacts

      - name: Attest OCI Image Build Provenance
        id: attest_image
        uses: actions/attest-build-provenance@v1
        with:
          subject-digest: ${{ inputs.image_digest }}
          subject-name: ${{ inputs.image_name_with_tag }} # Added: Provide the image name

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest CycloneDX SBOM for Image
        uses: actions/attest-sbom@v1
        with:
          subject-name: ${{ inputs.image_name_no_tag}}  # Do NOT include a tag as part of the image name -- the supplied digest subject-digest identifies the specific image being attested.
          subject-digest: ${{ inputs.image_digest }}  
          sbom-path: ./downloaded-artifacts/${{ inputs.sbom_cyclonedx_path }}
          push-to-registry: true

      - name: Attest SPDX SBOM for Image
        uses: actions/attest-sbom@v1
        with:
          subject-name: ${{ inputs.image_name_no_tag}} # Do NOT include a tag as part of the image name -- the supplied digest subject-digest identifies the specific image being attested.
          subject-digest: ${{ inputs.image_digest }}  
          sbom-path: ./downloaded-artifacts/${{ inputs.sbom_spdx_path }}
          push-to-registry: true

      - name: Attest Syft JSON SBOM for Image
        uses: actions/attest-sbom@v1
        with:
          subject-name: ${{ inputs.image_name_no_tag}} # Do NOT include a tag as part of the image name -- the supplied digest subject-digest identifies the specific image being attested.
          subject-digest: ${{ inputs.image_digest }}  
          sbom-path: ./downloaded-artifacts/${{ inputs.sbom_syft_json_path }}
          push-to-registry: true

      - name: Echo Attestation Details
        run: |
          echo "OCI Image Attestation ID: ${{ steps.attest_image.outputs.attestation-id }}"
          echo "Find attestations at: https://github.com/${{ github.repository }}/attestations"

